config/routes.rb
RorWorklog::Application.routes.draw do
  #
  # Paths
  #
  root :to => 'users#show', :constraints => lambda { |req| !req.session[:user_id].blank? }
  root :to => 'static_pages#home', :constraints => lambda { |req| req.session[:user_id].blank? }

  match '/home',        to: 'static_pages#home'
  match '/help',        to: 'static_pages#help'
  match '/signup',      to: 'users#new'
  match '/login',       to: 'sessions#new'
  match '/gplussignin', to: 'sessions#gpluscreate'
  match '/gplusassoc',  to: 'users#associate_gplus_id'
  match '/gpluscreate', to: 'users#create_from_gplus_id'
  match '/logout',      to: 'sessions#destroy'
  match '/profile',     to: 'users#show'

  #
  # Paths for user scoped access
  #
  scope '/:username', :constraints => ProfileConstraint do
    get '' => 'users#show', :as => 'user'
    put '' => 'users#update', :as => 'user'
    get 'edit' => 'users#edit', :as => 'edit_user'
    delete 'destory' => 'users#destroy', :as => 'destroy_user'
    resources :logs do
      resources :entries
    end
    resources :tags
    get 'logs/:id/tags/:name' => 'logs#show', :as => 'user_tagged_log'
  end
  resources :sessions
  resources :users, :only => [:create]

  #
  # Routes for Google+ Sign In
  #
  post "google_plus_sign_in/connect" => 'google_plus_sign_in#connect'
  get "google_plus_sign_in/disconnect" => 'google_plus_sign_in#disconnect'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :body, :id, :log_id, :tag_list

  belongs_to :log

  has_many :taggings
  has_many :tags, :through => :taggings

  validates_presence_of :body, :on => :create

  def self.tagged_with(name)
    Tag.find_by_name!(name).entries
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < InheritedResources::Base
  respond_to :html, :json

  rescue_from ActiveRecord::RecordNotFound, :with => :entry_not_found

  before_filter :require_user, :only => [:index, :new, :show, :create, :edit, :update, :destroy]
  before_filter :save_referer, :only => [:index, :edit, :destroy, :show]
  before_filter :logged_in_user, :only => [:index, :new, :show, :create, :edit, :update, :destroy]
  before_filter :generate_tags, :only => [:create]

  after_filter :entry_not_found, :only => [:edit, :destroy, :show, :update]
  after_filter :not_users_entry, :only => [:edit, :destroy, :update]

  belongs_to :log

  def index
    flash[:alert] = "Listing entries is not supported"
    @log = @request_user.logs.find(params[:log_id])
    redirect_to log_path(@log.user, @log)
    return false
  end

  def new
    flash[:alert] = "Standalone new entry form is not supported"
    @log = @request_user.logs.find(params[:log_id])
    redirect_to log_path(@log.user, @log)
    return false
  end

  def show
    flash[:alert] = "Standalone entry display is not supported"
    redirect_to log_path(resource.log.user, resource.log)
    return false
  end

  def edit
    flash[:alert] = "Standalone edit entry form is not supported"
    redirect_to log_path(resource.log.user, resource.log)
    return false
  end

  def create
    create! { log_path(resource.log.user, resource.log) }
  end

  def update
    update! { log_path(resource.log.user, resource.log) }
  end

  def destroy
    destroy! { log_path(resource.log.user, resource.log) }
  end

  protected
    def collection
      @entries ||= end_of_association_chain.order(:created_at).page(params[:page]).per(3)
    end

  private
    def save_referer
      session[:return_to] ||= request.referer
      session[:return_to] ||= root_path # If empty, go to root
    end

    def entry_not_found
      unless @entry
        flash[:alert] = "Could not find entry with ID " + params[:username] + " within log ID " + params[:log_id]
        redirect_to session.delete(:return_to)
        return false
      end
    end

    def not_users_entry
      unless @entry.log.user == current_user
        flash[:alert] = "You are not to owner of this Log. You cannot edit entries within"
        redirect_to session.delete(:return_to)
        return false
      end
    end

    def logged_in_user
      @request_user = User.find_by_username(params[:username])
      @request_user == current_user
    end

    def generate_tags
      if (params[:tags]) then
        @tags = params[:tags].collect { |id| current_user.tags.find(id).first }
      end
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<%= div_for entry do %>
  <tr class="log_entry">
    <td class="span6 log_entry_body">
      <div class="log_entry_body_holder">
        <div class="log_entry_tags">
          <%= raw entry.tags.map { |t| link_to t.name,
            user_tagged_log_path(entry.log.user, entry.log, t.name),
            :style => "background-color: ##{t.color}"
          }.join('') %>
        </div>
        <div class="log_entry_time label label-info"><%= entry.created_at.to_s(:log_time) %></div>
        <div class="log_entry_delete badge badge-important">
          <%= link_to log_entry_path(entry.log.user, entry.log, entry),
                    :confirm => 'Are you sure you want to delete this entry?',
                    :method => :delete,
                    :rel => 'tooltip',
                    :title => 'Delete entry' do %>
        <i class="icon-remove"></i>
          <% end %>
        </div>
        <div class="log_entry_txt"><%= entry.body %></div>
      </div>
    </td>
  </tr>
<% end %>

app/views/entries/_form.html.erb
<%= form_for([@entry.log.user, @entry.log, @entry]) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

Listing of entries is not supported

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', log_entries_path(@entry.log.user, @entry.log) %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_log_entry_path(@entry.log.user, @entry.log, @entry) %> |
<%= link_to 'Back', log_entries_path(@entry.log.user, @entry.log) %>