config/routes.rb
RorWorklog::Application.routes.draw do
  #
  # Paths
  #
  root :to => 'users#show', :constraints => lambda { |req| !req.session[:user_id].blank? }
  root :to => 'static_pages#home', :constraints => lambda { |req| req.session[:user_id].blank? }

  match '/home',        to: 'static_pages#home'
  match '/help',        to: 'static_pages#help'
  match '/signup',      to: 'users#new'
  match '/login',       to: 'sessions#new'
  match '/gplussignin', to: 'sessions#gpluscreate'
  match '/gplusassoc',  to: 'users#associate_gplus_id'
  match '/gpluscreate', to: 'users#create_from_gplus_id'
  match '/logout',      to: 'sessions#destroy'
  match '/profile',     to: 'users#show'

  #
  # Paths for user scoped access
  #
  scope '/:username', :constraints => ProfileConstraint do
    get '' => 'users#show', :as => 'user'
    put '' => 'users#update', :as => 'user'
    get 'edit' => 'users#edit', :as => 'edit_user'
    delete 'destory' => 'users#destroy', :as => 'destroy_user'
    resources :logs do
      resources :entries
    end
    resources :tags
    get 'logs/:id/tags/:name' => 'logs#show', :as => 'user_tagged_log'
  end
  resources :sessions
  resources :users, :only => [:create]

  #
  # Routes for Google+ Sign In
  #
  post "google_plus_sign_in/connect" => 'google_plus_sign_in#connect'
  get "google_plus_sign_in/disconnect" => 'google_plus_sign_in#disconnect'
end

app/models/user.rb
include ActiveModel::WorklogSecurePassword
class User < ActiveRecord::Base

  attr_accessible :created_at, :username, :email, :fullname, :id,
                  :password_digest, :password, :password_confirmation,
                  :avatar, :avatar_cache, :remove_avatar,
                  :gplus_id, :gplus_refresh_token, :gplus_display_name, :gplus_profile_url,
                  :gplus_avatar_url

  #
  # Validate password only for native accounts, not for Google+ connections
  #
  worklog_has_secure_password :validations => false

  validates_presence_of :username
  validates_presence_of :fullname
  validates_presence_of :email
  validates_presence_of :password_digest, :on => :create, :if => :is_native_account?

  validates_uniqueness_of :username
  validates_uniqueness_of :email
  validates_uniqueness_of :gplus_id, :if => :has_gplus_account?

  mount_uploader :avatar, AvatarUploader

  has_one :avatar
  has_many :logs
  has_many :entries, :through => :logs
  has_many :tags

  def to_param
    username
  end

  #
  # 
  #
  def is_native_account?
    logger.debug "GPLUS_ID: #{self.gplus_id}"
    self.gplus_id == nil
  end
  def has_gplus_account?
    logger.debug "GPLUS_ID: #{self.gplus_id}"
    self.gplus_id != nil
  end

  #
  # Avatar variations
  #
  def gplus_avatar_thumb_url
    self.gplus_avatar_url + "sz=100"
  end
  def gplus_avatar_tiny_url
    self.gplus_avatar_url + "sz=32"
  end
  def gplus_avatar_badge_url
    self.gplus_avatar_url + "sz=16"
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  include GooglePlusSignInHelper

  respond_to :html, :json

  before_filter :require_user, :only => [:index, :show, :edit, :update, :update_gplus_id, :destroy]
  before_filter :already_logged_in, :only => [:new]
  before_filter :no_user_listing, :only => [:index]
  before_filter :user_profile_url, :only => [:show]
  before_filter :load_belongings, :only => [:show]

  def create
    create! { logout_path  }
  end

  def associate_gplus_id
    resource[:gplus_id] = session[:gplus_id]
    resource[:gplus_refresh_token] = session[:token].to_hash[:refresh_token]

    $gplus_client = GooglePlusSignInHelper::GooglePlusClient.new
    @gplus = $gplus_client.get_profile(session, resource[:gplus_id])

    resource[:gplus_display_name] = @gplus[:name]
    resource[:gplus_profile_url] = @gplus[:profile_url]
    resource[:gplus_avatar_url] = @gplus[:img_url]

    update!
    flash[:notice] = "Associated Google+ ID " + resource[:gplus_id] + " to " + current_user.fullname
    redirect_to '/' and return
  end

  def new
    if session[:gplus_id].blank?
      new!
    else
      @user = User.new( :gplus_id => session[:gplus_id],
                        :gplus_refresh_token => session[:token].to_hash[:refresh_token])

      $gplus_client = GooglePlusSignInHelper::GooglePlusClient.new
      @gplus = $gplus_client.get_profile(session, @user[:gplus_id])

      @user[:fullname] = @gplus[:name]
      @user[:gplus_display_name] = @gplus[:name]
      @user[:gplus_profile_url] = @gplus[:profile_url]
      @user[:gplus_avatar_url] = @gplus[:img_url]
      logger.debug "USER: #{@user.to_yaml}"
    end
  end

  def update
    resource.avatar.store!
    update!
  end

  def destroy
    flash[:alert] = "User destruction not supported"
    redirect_to "/#{resource.username}" and return
  end

  private

  def resource
    if params.has_key?(:username)
      @user = User.find_by_username(params[:username])
    else
      @user = current_user
    end
  end

  def already_logged_in
    if current_user
      flash[:notice] = "You are already logged as " + current_user.fullname
      redirect_to '/' and return
    end
  end

  def user_profile_url
    unless params.has_key?(:username)
      redirect_to "/#{current_user.username}"
    end
  end

  def no_user_listing
    flash[:alert] = "User listing is not allowed"
    redirect_to '/' and return
  end

  def load_belongings
    unless resource
      flash[:alert] = "User not found"
      redirect_to '/' and return
    end
    @logs = resource.logs.order(:created_at).page(params[:page]).per(10)
    @tags = resource.tags.order(:name) # .page(params[:page]).per(10)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => {:multipart => true} do |f| %>
  <% if @user.errors.any? %>
    <div class="well">
      <b><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</b>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li class="text-error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'shared/gplussignin_button' %>
  <br>
  <hr>
  <dl class="dl-horizontal">
    <dt><%= f.label :fullname %></dt>
    <dd><%= f.text_field :fullname %></dd>
  </dl>
  <dl class="dl-horizontal">
    <dt><%= f.label :username %></dt>
    <dd><%= f.text_field :username, :disabled => !@user.username.blank? %></dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><%= f.label :email %></dt>
    <dd><%= f.email_field :email %></dd>
  </dl>

  <% if @user.is_native_account? %>

  <dl class="dl-horizontal">
    <dt><%= f.label :password %></dt>
    <dd><%= f.password_field :password %></dd>
  </dl>
  <% if @user.errors.has_key?(:password_confirmation) %>
  <dl class="dl-horizontal control-group error">
  <% else %>
  <dl class="dl-horizontal">
  <% end %>
    <dt><%= f.label :password_confirmation %></dt>
      <dd>
      <% if @user.errors.has_key?(:password_confirmation) %>
        <%= f.password_field :password_confirmation, :id => 'inputError' %>
        <div class="help-inline"><%= @user.errors.get(:password_confirmation) %></div>
      <% else %>
        <%= f.password_field :password_confirmation %>
      <% end %>
      </dd>
  </dl>
  <dl class="dl-horizontal">
    <dt><%= f.label :avatar %></dt>
    <dd>
      <%= f.file_field :avatar %>
      <%= f.hidden_field :avatar_cache %>
      <%= image_tag(@user.avatar.thumb.url, :class => 'img-polaroid') if @user.avatar? %>
    </dd>
  </dl>
  <% else %>
    <dt><%= f.label :avatar %></dt>
    <dd>
      <%= image_tag(@user.gplus_avatar_thumb_url, :class => 'img-polaroid') %>
    </dd>
    <%= f.hidden_field :gplus_id, :value => @user.gplus_id %>
    <%= f.hidden_field :gplus_display_name, :value => @user.gplus_display_name %>
    <%= f.hidden_field :gplus_profile_url, :value => @user.gplus_profile_url %>
    <%= f.hidden_field :gplus_avatar_url, :value => @user.gplus_avatar_url %>
  <% end %>
  <div class="actions">
    <%= f.submit ((action_name == 'edit') ? 'Update User' : 'Create User'), :class => 'btn btn-primary pull-right' %>
    <%= link_to 'Cancel', root_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User - ' + "#{@user.fullname}") %>
<% provide(:page_heading, 'Editing user ' + "#{@user.fullname}") %>

<% if @user.id == current_user.id %>
  <%= render 'form' %>
<% else %>
  <h2>You (id=<%= current_user.id %>) are not allowed to edit other users (id=<%= @user.id %>)</h2>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'New User') %>
<% provide(:page_heading, "Join #{Settings.app_name}") %>
<% content_for :signup_link_style do %>
class="active"
<% end %>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, 'User Info - ' + "#{@user.fullname}") %>

<% content_for :breadcrumbs do %>
<div class="row">
  <div class="span7">
  <ul class="breadcrumb">
    <%= render 'shared/breadcrumb_user_info' %>
    <%= link_to 'User settings', edit_user_path(@user), :class => 'btn btn-mini pull-right' %>
  </ul>
  </div><!-- /.span7 -->
</div><!-- /.row -->
<% end %>

<div class="row">
  <div class="span5">
    <dl class="dl-horizontal">
      <dt>Name</dt><dd><%= @user.fullname %></dd>
      <dt>Username</dt><dd><%= @user.username %></dd>
      <dt>E-mail</dt><dd><%= @user.email %></dd>
      <dt>Member since</dt><dd><%= @user.created_at.to_s(:member_since) %></dd>
    </dl>
    <%= render 'shared/gplussignin_button' %>
  </div><!-- /.span5 -->
  <div class="span2">
  <% if session[:gplus_id] %>
    <%= image_tag(@user.gplus_avatar_thumb_url, :class => 'img-polaroid') %>
  <% else %>
    <%= image_tag(@user.avatar.thumb.url, :class => 'img-polaroid') %>
  <% end %>
  </div><!-- /.span2 -->
</div><!-- /.row -->

<hr class="invisible">

<div class="row">
  <div class="span2">
  </div><!-- /.span2 -->
</div><!-- /.row -->

<hr class="invisible">

<div class="row">
  <div class="span7">
    <ul class="breadcrumb">
      <li><strong>Logs</strong></li>
      <%= link_to 'Start a new Log', new_log_path(@user), :class => 'btn btn-mini pull-right' %>
    </ul>
    <%= paginate @logs %>
    <%= render @logs %>
  </div><!-- /.span7 -->
</div><!-- /.row -->

<hr class="invisible">

<div class="row">
  <div class="span7">
    <ul class="breadcrumb">
      <li><strong>Tags</strong></li>
      <%= link_to 'Create a new Tag', new_tag_path(@user), :class => 'btn btn-mini pull-right' %>
    </ul>
    <%= render @tags %>
  </div><!-- /.span7 -->
</div><!-- /.row -->