config/routes.rb
RorWorklog::Application.routes.draw do
  #
  # Paths
  #
  root :to => 'users#show', :constraints => lambda { |req| !req.session[:user_id].blank? }
  root :to => 'static_pages#home', :constraints => lambda { |req| req.session[:user_id].blank? }

  match '/home',        to: 'static_pages#home'
  match '/help',        to: 'static_pages#help'
  match '/signup',      to: 'users#new'
  match '/login',       to: 'sessions#new'
  match '/gplussignin', to: 'sessions#gpluscreate'
  match '/gplusassoc',  to: 'users#associate_gplus_id'
  match '/gpluscreate', to: 'users#create_from_gplus_id'
  match '/logout',      to: 'sessions#destroy'
  match '/profile',     to: 'users#show'

  #
  # Paths for user scoped access
  #
  scope '/:username', :constraints => ProfileConstraint do
    get '' => 'users#show', :as => 'user'
    put '' => 'users#update', :as => 'user'
    get 'edit' => 'users#edit', :as => 'edit_user'
    delete 'destory' => 'users#destroy', :as => 'destroy_user'
    resources :logs do
      resources :entries
    end
    resources :tags
    get 'logs/:id/tags/:name' => 'logs#show', :as => 'user_tagged_log'
  end
  resources :sessions
  resources :users, :only => [:create]

  #
  # Routes for Google+ Sign In
  #
  post "google_plus_sign_in/connect" => 'google_plus_sign_in#connect'
  get "google_plus_sign_in/disconnect" => 'google_plus_sign_in#disconnect'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :id, :name, :color, :user_id

  belongs_to :user

  has_many :taggings
  has_many :entries, :through => :taggings

  validates_presence_of :name, :on => :create
  validates_uniqueness_of :name, :scope => :user_id
  validates_presence_of :color, :on => :create
  validates_associated :user

  # def to_param
  #   name
  # end
end

app/controllers/tags_controller.rb
class TagsController < InheritedResources::Base
  respond_to :html, :json

  before_filter :logged_in_user, :only => [:new, :show, :create, :edit, :update, :destroy]

  belongs_to :user

  def create
    params[:tag][:color].gsub!(/^#/, "")
    create! { "/#{@user.username}" }
  end

  def update
    params[:tag][:color].gsub!(/^#/, "")
    update! { "/#{@user.username}" }
  end


  def destroy
    destroy! { "/#{@user.username}" }
  end

  protected
    def begin_of_association_chain
      @user = current_user;
    end

    def collection
      @tags ||= end_of_association_chain.order(:name) # .page(params[:page]).per(10)
    end

    def logged_in_user
      @request_user = User.find_by_username(params[:username])
      @request_user == current_user
    end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class="dl-horizontal">
    <dt><%= f.label :name %></dt>
    <dd><%= f.text_field :name %></dd>
  </dl>
   <dl class="dl-horizontal">
    <dt><%= f.label :color %></dt>
    <dd>
      <div class="input-append color" data-color="#<%= @tag.color %>" data-color-format="hex" id="tag_colorpicker">
        <%= f.text_field :color, :class => "span2", :readonly => true %>
        <span class="add-on"><i style="background-color: rgb(ccff00))"></i></span>
      </div>
    </dd>
  </dl>
  <div class="actions">
    <%= f.submit 'Create Tag', :class => 'btn btn-primary pull-right' %>
    <%= link_to 'Back', profile_path(), :class => 'btn' %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<%= div_for tag do %>
  <div class="tag_body" style="background-color: #<%= tag.color %>">
    <div class="tag_control badge badge-important">
      <%= link_to edit_tag_path(tag.user, tag),
                  :rel => 'tooltip',
                  :title => 'Edit tag' do %>
        <i class="icon-edit"></i>
      <% end %>
        &nbsp;
      <%= link_to tag_path(tag.user, tag),
                  :confirm => 'Are you sure you want to delete this tag?',
                  :method => :delete,
                  :rel => 'tooltip',
                  :title => 'Delete tag' do %>
        <i class="icon-remove"></i>
      <% end %>
    </div>
    <%= tag.name %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<% provide(:title, 'Edit Tag') %>
<% content_for :page_heading do %>
  <h3>Tag Settings</h3>
<% end %>

<% content_for :breadcrumbs do %>
<div class="row">
  <div class="span7">
  <ul class="breadcrumb">
    <li><%= link_to '/' do %><%= render 'shared/breadcrumb_user_info' %><% end %>
    <span class="divider">/</span></li>
    <li class="active"><%= @tag.name %></li>
  </ul>
  </div><!-- /.span7 -->
</div><!-- /.row -->
<% end %>

<div class="row">
  <div class="span7">

    <%= render 'form' %>

  </div><!-- /.span7 -->
</div><!-- /.row -->

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<% provide(:title, 'New Tag') %>
<% content_for :page_heading do %>
  <h3>Create a New Tag</h3>
<% end %>

<% content_for :breadcrumbs do %>
<div class="row">
  <div class="span7">
  <ul class="breadcrumb">
    <li><%= link_to '/' do %><%= render 'shared/breadcrumb_user_info' %><% end %>
    <span class="divider">/</span></li>
    <li class="active">Create Tag</li>
  </ul>
  </div><!-- /.span7 -->
</div><!-- /.row -->
<% end %>

<div class="row">
  <div class="span7">

    <%= render 'form' %>

  </div><!-- /.span7 -->
</div><!-- /.row -->

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>