config/routes.rb
RorWorklog::Application.routes.draw do
  #
  # Paths
  #
  root :to => 'users#show', :constraints => lambda { |req| !req.session[:user_id].blank? }
  root :to => 'static_pages#home', :constraints => lambda { |req| req.session[:user_id].blank? }

  match '/home',        to: 'static_pages#home'
  match '/help',        to: 'static_pages#help'
  match '/signup',      to: 'users#new'
  match '/login',       to: 'sessions#new'
  match '/gplussignin', to: 'sessions#gpluscreate'
  match '/gplusassoc',  to: 'users#associate_gplus_id'
  match '/gpluscreate', to: 'users#create_from_gplus_id'
  match '/logout',      to: 'sessions#destroy'
  match '/profile',     to: 'users#show'

  #
  # Paths for user scoped access
  #
  scope '/:username', :constraints => ProfileConstraint do
    get '' => 'users#show', :as => 'user'
    put '' => 'users#update', :as => 'user'
    get 'edit' => 'users#edit', :as => 'edit_user'
    delete 'destory' => 'users#destroy', :as => 'destroy_user'
    resources :logs do
      resources :entries
    end
    resources :tags
    get 'logs/:id/tags/:name' => 'logs#show', :as => 'user_tagged_log'
  end
  resources :sessions
  resources :users, :only => [:create]

  #
  # Routes for Google+ Sign In
  #
  post "google_plus_sign_in/connect" => 'google_plus_sign_in#connect'
  get "google_plus_sign_in/disconnect" => 'google_plus_sign_in#disconnect'
end

app/models/log.rb
class Log < ActiveRecord::Base
  attr_accessible :description, :id, :name, :user_id

  belongs_to :user
  has_many :entries
  has_many :tags

  validates_presence_of :name, :on => :create
  validates_presence_of :description, :on => :create
  validates_uniqueness_of :name, :scope => :user_id
  validates_associated :user, :entries
end

app/controllers/logs_controller.rb
class LogsController < InheritedResources::Base
  respond_to :html, :json

  # rescue_from ActiveRecord::RecordNotFound, :with => :log_not_found

  # before_filter :require_user, :only => [:new, :show, :create, :edit, :update, :destroy]
  before_filter :save_referer, :only => [:edit, :destroy, :show]
  before_filter :load_entries, :only => [:show]
  before_filter :logged_in_user, :only => [:index, :new, :show, :create, :edit, :update, :destroy]

  after_filter :log_not_found, :only => [:edit, :destroy, :show]
  after_filter :not_users_log, :only => [:edit, :destroy]

  belongs_to :user

  def index
    flash[:alert] = "Listing logs is not supported"
    redirect_to user_path(@request_user.username)
    return false
  end

  def update
    update! { log_path(resource.user, resource) }
  end

  def create
    create! { log_path(resource.user, resource) }
  end

  def destroy
    destroy! { "/#{@user.username}" }
  end

  protected
    def begin_of_association_chain
      @user = current_user;
    end

    def collection
      @logs ||= end_of_association_chain.order(:created_at).page(params[:page]).per(10)
    end

  private
    def save_referer
      session[:return_to] ||= request.referer
      session[:return_to] ||= root_path # If empty, go to root
    end

    def log_not_found
      unless @log
        flash[:alert] = "Could not find log with ID " + params[:id]
        redirect_to session.delete(:return_to)
        return false
      end
    end

    def logged_in_user
      @request_user = User.find_by_username(params[:username])
      @request_user == current_user
    end

    def not_users_log
      unless @log.user == current_user
        flash[:alert] = "You are not to owner of this log. You cannot edit it"
        redirect_to session.delete(:return_to)
        return false
      end
    end

    def load_entries
      @resource_entries = resource.entries
      #
      # Filter by tag name if provided
      #
      if (!params[:name].blank?) then
        @resource_entries = @resource_entries.tagged_with(params[:name])
      end
      @resource_entries = @resource_entries.order('created_at DESC').page(params[:page]).per(10)
      @entry_groups = @resource_entries.group_by { |m| m.created_at.beginning_of_day }
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class="dl-horizontal">
    <dt><%= f.label :name %></dt>
    <dd><%= f.text_field :name %></dd>
  </dl>
   <dl class="dl-horizontal">
    <dt><%= f.label :description %></dt>
    <dd><%= f.text_area :description, :rows => "3", :class => 'input-block-level' %></dd>
  </dl>
  <div class="actions">
    <%= f.submit 'Create Log', :class => 'btn btn-primary pull-right' %>
    <%= link_to 'Back', profile_path(), :class => 'btn' %>
  </div>
<% end %>

app/views/logs/_log.html.erb
<%= div_for log do %>
  <div class="span3 log_body">
    <div class="log_control badge badge-important">
      <%= link_to edit_log_path(log.user, log),
                  :rel => 'tooltip',
                  :title => 'Edit log' do %>
        <i class="icon-edit"></i>
      <% end %>
        &nbsp;
      <%= link_to log_path(log.user, log),
                  :confirm => 'Are you sure you want to delete this log?',
                  :method => :delete,
                  :rel => 'tooltip',
                  :title => 'Delete log' do %>
        <i class="icon-remove"></i>
      <% end %>
    </div>
    <h3><%= link_to log.name, log_path(log.user, log) %></h3>
    <%= log.description %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<% provide(:title, 'Edit Log') %>
<% content_for :page_heading do %>
  <h3>Log Settings</h3>
<% end %>

<% content_for :breadcrumbs do %>
<div class="row">
  <div class="span7">
  <ul class="breadcrumb">
    <li><%= link_to '/' do %><%= render 'shared/breadcrumb_user_info' %><% end %>
    <span class="divider">/</span></li>
    <li class="active"><%= @log.name %></li>
  </ul>
  </div><!-- /.span7 -->
</div><!-- /.row -->
<% end %>

<div class="row">
  <div class="span7">

    <%= render 'form' %>

  </div><!-- /.span7 -->
</div><!-- /.row -->

app/views/logs/index.html.erb
<h1>Listing logs</h1>

Not allowed

app/views/logs/new.html.erb
<% provide(:title, 'New Log') %>
<% content_for :page_heading do %>
  <h3>Create a New Log</h3>
<% end %>

<% content_for :breadcrumbs do %>
<div class="row">
  <div class="span7">
  <ul class="breadcrumb">
    <li><%= link_to '/' do %><%= render 'shared/breadcrumb_user_info' %><% end %>
    <span class="divider">/</span></li>
    <li class="active">Create Log</li>
  </ul>
  </div><!-- /.span7 -->
</div><!-- /.row -->
<% end %>

<div class="row">
  <div class="span7">

    <%= render 'form' %>

  </div><!-- /.span7 -->
</div><!-- /.row -->

app/views/logs/show.html.erb
<% provide(:title, "Log - #{@log.name}") %>

<% content_for :breadcrumbs do %>
<div class="row">
  <div class="span7">
  <ul class="breadcrumb">
    <li id="entry_input_form_toggle"><a href="#" rel="tooltip" title="Toggle new entry"><i class="icon-edit"></i></a></li>
    <li><%= link_to '/' do %><%= render 'shared/breadcrumb_user_info' %><% end %>
    <span class="divider">/</span></li>
    <% if params[:name].blank? %>
      <li class="active"><%= @log.name %></li>
    <% else %>
      <li class="active"><%= link_to log_path(@log.user,@log) do %><%= @log.name %><% end %></li>
      <span class="divider">/</span></li>
      <li class="active"><%= params[:name] %></li>
    <% end %>
  </ul>
  </div><!-- /.span7 -->
</div><!-- /.row -->
<% end %>

<div class="row">
  <div class="well span7" id="entry_input_form">
    <%= form_tag log_entries_path(@log.user, @log) do %>
      <%= text_area_tag 'entry[body]', nil, :rows => 3, :class => 'input-block-level' %>
      <%= select_tag "entry[tag_list]", options_for_select(@log.user.tags.collect {|t| [t.name, t.name]}),
                     :id => 'entry_tags', :multiple => true %>
      <%= submit_tag "Submit", :class => "btn btn-primary pull-right" %>
    <% end %>
  </div>

  <div class="span7">
    <%= paginate @resource_entries %>
    <table class="table" style="margin: 0px">
      <% @entry_groups.each { |key, value|
          @entries = value
      %>
      <tr>
        <td class="span1">
          <div class="log_time_month"><%= key.to_s(:log_time_mn) %></div>
          <div class="log_time_day"><%= key.to_s(:log_time_dy) %></div>
          <div class="log_time_year"><%= key.to_s(:log_time_yr) %></div>
        </td>
        <td class="span6">
          <table class="span6 log_entry_group">
            <%= render @entries %>
          </table>
        </td>
      </tr>
      <% } %>
    </table>
  </div><!-- /.span7 -->
</div><!-- /.row -->